name: Nightly Builds

on: workflow_dispatch

env:
  GO_VERSION: '1.19.2'
  
jobs:
  build:
    name: Build latest Flow Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Update Flow Go
        run: go get github.com/onflow/flow-go@master

      - name: Tidy up
        run: go mod tidy

      - name: Build
        run: go build -v ./...
        continue-on-error: true

      - name: Create issue on build failure
        if: ${{ failure() }}
        uses: peter-evans/create-issue@v3
        with:
          title: "Nightly Flow Go build failed"
          body: |
            "The build with the latest flow-go failed. Please investigate and fix the issue. cc @janezpodhostnik2 @j10100012
            
            Workflow Run: ${{ github.run_number }}
            Commit: ${{ github.sha }}
            Ref: ${{ github.ref }}"
